"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

Daniel Koska (koda86), Jun 02 2022
"""

def fibo(i):
    if i in {0, 1}:
        return i
    else:    
        return fibo(i-1) + fibo(i-2)
    
l = list()
for i in range(1, 40):
       
    if fibo(i) < 4e6:
        if fibo(i) % 2 == 0:
            l.append(fibo(i))

print(sum(l))
