# Problem 2: Even Fibonacci numbers
#
# Each new term in the Fibonacci sequence is generated by adding the previous two
# terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
#
# Daniel Koska (koda86), Aug 30 2021
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Use a recursive function to get the Fibonacci sequence
fibo <- function (fibo.seq, fibo.stop) {

  while (tail(fibo.seq, n=1) < fibo.stop) {
    if (length(fibo.seq) == 1) {
      seq.val <- 1
    } else {
      seq.val <- tail(fibo.seq, 2)[1]
    }

    fibo.seq <- c(fibo.seq, seq.val + tail(fibo.seq, n=1))
  }

  fibo.seq <- fibo.seq[1:length(fibo.seq)-1]

  return(fibo.seq)
}

fibo.seq <- 0
fibo.stop <- 4e6
fibonacci <- fibo(fibo.seq, fibo.stop)

mod <- function (x, y) {x %% y} # Find even numbers

even.idx <- mod(fibonacci, 2)
even <- fibonacci[even.idx==0]

sum(even)
